### PR TITLE
Add credo with a custom config

### PR DESCRIPTION
**Pull request by joeyrosztoczy**
@keathley figured I'd start by bringing in the full generated config and we can whittle away the stuff you're not a fan of in this pr <3

### CODE REVIEW

**Comment by keathley** [comment]
So, I read through all of the credo checks to figure out what they do. Based on that here's the `.credo.exs` file with the stuff that I think makes the most sense to keep enabled: https://gist.github.com/keathley/acf81b3e6033361f6e72531194121465

**Comment by keathley** [comment]
@joeyrosztoczy I've ci to norm so feel free to add to rebase this branch against master and add the credo checks to the build process as well.

**Comment by joeyrosztoczy** [comment]
@keathley since we now have 2 - 3 checks with compile + test + credo I added caching to the build step and re-use the build in test and credo.

**_LMK if that's overkill and I can revert and we could rebuild in credo or we could just run them sequentially in one step. Just thought I'd suggest it but no worries if not_**

This would also ask for a CIRCLE_CI_CACHE_VERSION env var set in circleci (which could be used to bust the cache quickly and easily without a code change) which I could also remove.

I don't see the check's integrated with the project yet just FYI - there might be something we need to configure on the Github <-> CircleCI configuration to ensure build pass on the PR

**Comment by keathley** [comment]
@joeyrosztoczy sorry for the delay. This looks great to me. Would you mind rebasing your branch against master? It should run against CI now.

**Comment by joeyrosztoczy** [comment]
> @joeyrosztoczy sorry for the delay. This looks great to me. Would you mind rebasing your branch against master? It should run against CI now.

You bet! Going to close and reopen got my remote out of sync

**Pull request closed without merging**
