### PR TITLE
primitive type generators (is_float test)

### PR DESCRIPTION
**Pull request by joeyrosztoczy**
Hi Chris! I really enjoyed your talk at ElixirConf. Inter-service contracts are something I feel like get implemented from scratch in so many api style code bases (and ultimately is solved by throwing hours at bugs or custom casting/validation/whatever modules).

I'll definitely be trying out Norm and look forward to checking out some of the resources you provided in the talk!

I guess I mostly wanted to open this PR to see how I could contribute (rather than an issue). I noticed one of your asks for early contributions was supporting generators for other primitive types. I'd love to help there! Curious if a PR adding some of them in would be helpful.

I haven't really contributed to open source or libraries, so I thought I'd put up a WIP where I added support for ```gen(spec(is_float()))```. I'm not sure if this is what you had in mind for that task / TODO.

If you had something else in mind, I'd love to get feedback and still try and help contribute! If this is OK, I'll start including other primitives!

P.s. sorry for the spacing in the files, I think that was my auto-formatter. LMK if you'd also like me to remove the noise or if its OK

### CODE REVIEW

**Comment by keathley** [comment]
Hey @joeyrosztoczy this looks great. I'll set up the formatter on this project so you won't have to churn those files. Once that's done if you wouldn't mind rebasing we should be good to merge this :+1:

**Comment by joeyrosztoczy** [comment]
Sweet, @keathley happy to configure / format as well if you want in a separate PR as well and rebase this one after. I would imagine that's kind of an annoying PR to get as a maintainer though because its essentially all noise but need to see if anythings materially changed, so no worries if not!

**Comment by keathley** [comment]
No worries @joeyrosztoczy. I've run the formatter on the project so if you want to rebase your branch it should merge cleanly now :+1:

**Comment by joeyrosztoczy** [comment]
Should be good to go thanks!

**Pull request merged**
